# Generated by Django 4.2.7 on 2023-11-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techservice', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='method_recovery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techservice.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='node_failure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techservice.failure', verbose_name='Узел отказа'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techservice.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Машина'),
        ),
    ]
